name: Hexo CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
          
      - name: Installation Environment
        uses: actions/setup-node@master
        with:
          node-version: 12.x  

      - name: replace cdn url
        id: replace
        run: |
          tagname=$(openssl rand -hex 4)
          sed -i "s/nocilol.me/nocilol.me@$tagname/g" _config.yml
          sed -i "s/nocilol.me/nocilol.me@$tagname/g" themes/geek/_config.yml
          echo "::set-output name=tagname::$tagname"

      - name: Installation
        run: |
          npm install
          npm install -g hexo-cli
          
      - name: Generate
        run: hexo clean && hexo g

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
          cname: nocilol.me

      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.replace.outputs.tagname }}
          release_name: ${{ steps.replace.outputs.tagname }}
          body: Automatic generated
          draft: false
          prerelease: true
